-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.application
(
    application_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    name text,
    priority_id integer,
    status_id integer,
    description text,
    delegated_id integer,
    is_unfinished boolean,
    department_id integer,
    types_of_works integer,
    empl_assigned_complexity integer,
    created_at timestamp with time zone,
    executor_at timestamp with time zone,
    is_expired boolean,
    deadline timestamp with time zone,
    work_at timestamp with time zone,
    updated_at timestamp with time zone,
    finished_at timestamp with time zone,
    archived_at timestamp with time zone,
    result_text text,
    executor_comment text,
    manager_comment text,
    previous_executor_id integer,
    closed_by_id integer,
    priority_score real,
    deadline_notified boolean,
    escalation_notified boolean,
    PRIMARY KEY (application_id)
);

-- Журнал переходов статусов заявки. Пишется подсистемой управления при каждой
-- смене статуса; основа для аналитики и метрик времени (см. docs/backend-functions.md).
CREATE TABLE IF NOT EXISTS public.application_status_history
(
    id              integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    application_id  integer,
    from_status_id  integer,
    to_status_id    integer,
    changed_at      timestamp with time zone NOT NULL,
    by_employee_id  integer,
    reason          text,
    PRIMARY KEY (id)
);

-- Настройки расчёта приоритета (одна строка, id=1). Заменяет прежний in-memory dict.
CREATE TABLE IF NOT EXISTS public.priority_settings
(
    id             integer NOT NULL,
    department     jsonb NOT NULL DEFAULT '{}'::jsonb,
    manager_author jsonb NOT NULL DEFAULT '{}'::jsonb,
    deadline       real  NOT NULL DEFAULT 0.2,
    urgent_bonus   real  NOT NULL DEFAULT 0.5,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.priority
(
    priority_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    value real,
    name text,
    PRIMARY KEY (priority_id)
);

CREATE TABLE IF NOT EXISTS public.status
(
    status_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    name text,
    PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS public.photo
(
    photo_id     integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    s3_key       character varying(1000) NOT NULL,
    name         character varying(500)  NOT NULL DEFAULT 'upload',
    content_type character varying(100)  NOT NULL DEFAULT 'application/octet-stream',
    size_bytes   integer,
    uploaded_at  timestamp with time zone NOT NULL DEFAULT NOW(),
    application_id integer,
    PRIMARY KEY (photo_id)
);

CREATE TABLE IF NOT EXISTS public.delegated
(
    delegated_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    delegated_by text,
    delegated_by_employee integer,
    delegated_from text,
    delegated_to text,
    comment text,
    created_at timestamp with time zone,
    decision text,
    decided_at timestamp with time zone,
    application_id integer,
    PRIMARY KEY (delegated_id)
);

CREATE TABLE IF NOT EXISTS public.department
(
    department_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "group" text,
    value real,
    name text,
    delegated_to_same_dep boolean,
    empl_appl_delay integer,
    deadline_notification real,
    PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS public.types_of_works
(
    type_of_works_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    name text,
    complexity_value integer,
    department_id integer,
    PRIMARY KEY (type_of_works_id)
);

CREATE TABLE IF NOT EXISTS public.complexity_value
(
    complexity_value_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 ),
    name text,
    PRIMARY KEY (complexity_value_id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    department_id integer,
    post_grade_id integer,
    role_id integer,
    fio text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    is_active boolean,
    PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public.post
(
    post_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    name text,
    is_top boolean,
    PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS public.grade
(
    grade_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 ),
    name text,
    PRIMARY KEY (grade_id)
);

CREATE TABLE IF NOT EXISTS public.post_grade
(
    post_grade_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    post_post_id integer,
    grade_grade_id integer,
    PRIMARY KEY (post_grade_id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    role_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    name text,
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.employee_to_application
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    role_id integer,
    application_id integer,
    employee_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notification
(
    notification_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    text text,
    created_at timestamp with time zone,
    employee_id integer,
    is_read boolean,
    application_id integer,
    PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.type_of_work_to_grade
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    type_of_works_id integer,
    grade_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (priority_id)
    REFERENCES public.priority (priority_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (status_id)
    REFERENCES public.status (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (types_of_works)
    REFERENCES public.types_of_works (type_of_works_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (delegated_id)
    REFERENCES public.delegated (delegated_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (previous_executor_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (closed_by_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.photo
    ADD FOREIGN KEY (application_id)
    REFERENCES public.application (application_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.delegated
    ADD FOREIGN KEY (application_id)
    REFERENCES public.application (application_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.types_of_works
    ADD FOREIGN KEY (complexity_value)
    REFERENCES public.complexity_value (complexity_value_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.types_of_works
    ADD FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (post_grade_id)
    REFERENCES public.post_grade (post_grade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.post_grade
    ADD FOREIGN KEY (post_post_id)
    REFERENCES public.post (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.post_grade
    ADD FOREIGN KEY (grade_grade_id)
    REFERENCES public.grade (grade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_to_application
    ADD FOREIGN KEY (role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_to_application
    ADD FOREIGN KEY (application_id)
    REFERENCES public.application (application_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_to_application
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.notification
    ADD FOREIGN KEY (application_id)
    REFERENCES public.application (application_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.notification
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.type_of_work_to_grade
    ADD FOREIGN KEY (type_of_works_id)
    REFERENCES public.types_of_works (type_of_works_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.type_of_work_to_grade
    ADD FOREIGN KEY (grade_id)
    REFERENCES public.grade (grade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.delegated
    ADD FOREIGN KEY (delegated_by_employee)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
