-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.application DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.application DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.application DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.application DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.application DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.application DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.photo DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.types_of_works DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.types_of_works DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.employee DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.employee DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.post_grade DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.post_grade DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.employee_to_application DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.employee_to_application DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.employee_to_application DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.application;

CREATE TABLE IF NOT EXISTS public.application
(
    application_id serial,
    name text,
    priority_id integer,
    status_id integer,
    description text,
    photo_id integer,
    delegated_id integer,
    is_unfinished boolean,
    department_id integer,
    types_of_works integer,
    empl_assigned_complexity integer,
    created_at timestamp without time zone,
    executor_at timestamp without time zone,
    is_expired boolean,
    deadline timestamp without time zone,
    work_at timestamp without time zone,
    updated_at timestamp without time zone,
    finished_at timestamp without time zone,
    result_text text,
    PRIMARY KEY (application_id)
);

DROP TABLE IF EXISTS public.priority;

CREATE TABLE IF NOT EXISTS public.priority
(
    priority_id serial,
    value real,
    name text,
    PRIMARY KEY (priority_id)
);

DROP TABLE IF EXISTS public.status;

CREATE TABLE IF NOT EXISTS public.status
(
    status_id serial,
    name text,
    PRIMARY KEY (status_id)
);

DROP TABLE IF EXISTS public.photo;

CREATE TABLE IF NOT EXISTS public.photo
(
    photo_id serial,
    value character varying(1000000),
    application_id integer,
    PRIMARY KEY (photo_id),
    UNIQUE (application_id)
);

DROP TABLE IF EXISTS public.delegated;

CREATE TABLE IF NOT EXISTS public.delegated
(
    delegated_id serial,
    delegated_by text,
    delegated_from integer,
    delegated_to integer,
    comment text,
    created_at timestamp without time zone,
    PRIMARY KEY (delegated_id)
);

DROP TABLE IF EXISTS public.department;

CREATE TABLE IF NOT EXISTS public.department
(
    department_id serial,
    "group" text,
    value real,
    name text,
    delegated_to_same_dep boolean,
    empl_appl_delay real,
    deadline_notification real,
    PRIMARY KEY (department_id)
);

DROP TABLE IF EXISTS public.types_of_works;

CREATE TABLE IF NOT EXISTS public.types_of_works
(
    type_of_works_id serial,
    name text,
    complexity_value integer,
    department_id integer,
    PRIMARY KEY (type_of_works_id)
);

DROP TABLE IF EXISTS public.complexity_value;

CREATE TABLE IF NOT EXISTS public.complexity_value
(
    complexity_value_id serial,
    name text,
    PRIMARY KEY (complexity_value_id)
);

DROP TABLE IF EXISTS public.employee;

CREATE TABLE IF NOT EXISTS public.employee
(
    employee_id serial,
    department_id integer,
    post_id integer,
    fio text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    PRIMARY KEY (employee_id)
);

DROP TABLE IF EXISTS public.post;

CREATE TABLE IF NOT EXISTS public.post
(
    post_id serial,
    name text,
    is_top boolean,
    PRIMARY KEY (post_id)
);

DROP TABLE IF EXISTS public.grade;

CREATE TABLE IF NOT EXISTS public.grade
(
    grade_id serial,
    name text,
    PRIMARY KEY (grade_id)
);

DROP TABLE IF EXISTS public.post_grade;

CREATE TABLE IF NOT EXISTS public.post_grade
(
    post_post_id integer,
    grade_grade_id integer
);

DROP TABLE IF EXISTS public.role;

CREATE TABLE IF NOT EXISTS public.role
(
    role_id serial,
    name text,
    PRIMARY KEY (role_id)
);

DROP TABLE IF EXISTS public.employee_to_application;

CREATE TABLE IF NOT EXISTS public.employee_to_application
(
    id serial,
    role_id integer,
    application_id integer,
    employee_id integer,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.notification;

CREATE TABLE IF NOT EXISTS public.notification
(
    notification_id serial,
    text text,
    created_at timestamp without time zone,
    PRIMARY KEY (notification_id)
);

ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (priority_id)
    REFERENCES public.priority (priority_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (status_id)
    REFERENCES public.status (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (photo_id)
    REFERENCES public.photo (photo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (types_of_works)
    REFERENCES public.types_of_works (type_of_works_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application
    ADD FOREIGN KEY (delegated_id)
    REFERENCES public.delegated (delegated_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.photo
    ADD FOREIGN KEY (application_id)
    REFERENCES public.application (application_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.types_of_works
    ADD FOREIGN KEY (complexity_value)
    REFERENCES public.complexity_value (complexity_value_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.types_of_works
    ADD FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (post_id)
    REFERENCES public.post (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (department_id)
    REFERENCES public.department (department_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.post_grade
    ADD FOREIGN KEY (post_post_id)
    REFERENCES public.post (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.post_grade
    ADD FOREIGN KEY (grade_grade_id)
    REFERENCES public.grade (grade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_to_application
    ADD FOREIGN KEY (role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_to_application
    ADD FOREIGN KEY (application_id)
    REFERENCES public.application (application_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee_to_application
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;